# Setup
title:        Theory Division Wiki
tagline:      A wiki for the Theory Division!
remote_theme: "mmistakes/minimal-mistakes@4.17.0"
baseurl:      "/"
paginate:     1
locale:       "en"
permalink:    /:title/
# About/contact
author:
  name:       Author name
  url:        https://www.lerner.ccf.org/thor/scott/lab/

# Define non-post collections
collections:
  journal_club:
    output: true
  lab_meeting:
    output: true

# Gems
gems:
  - jekyll-paginate
  
plugins:
  - jekyll-include-cache

#Others
markdown: kramdown
